### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by allinshang** [ecomfe/vue-echarts#160]
操作步骤：
1.git clone https://github.com/Justineo/vue-echarts.git
2.cd vue-echarts
3.npm install
4.npm run dev
报错如下：

```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\nodejs\\node.exe',
1 verbose cli   'D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@5.3.0
3 info using node@v8.4.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vue-echarts@2.5.0~predev: vue-echarts@2.5.0
6 info lifecycle vue-echarts@2.5.0~dev: vue-echarts@2.5.0
7 verbose lifecycle vue-echarts@2.5.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle vue-echarts@2.5.0~dev: PATH: D:\nodejs\node_modules\npm\bin\node-gyp-bin;E:\study\vue\vue-echarts\node_modules\.bin;D:\Ruby23-x64\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;D:\jdk1.8.0_101\bin;D:\apache-ant-1.8.2\bin;D:\TortoiseSVN\bin;D:\nodejs\;D:\Git\cmd;C:\Users\hyshang\AppData\Roaming\npm;D:\Android\sdk\tools;D:\Android\sdk\platform-tools
9 verbose lifecycle vue-echarts@2.5.0~dev: CWD: E:\study\vue\vue-echarts
10 silly lifecycle vue-echarts@2.5.0~dev: Args: [ '/d /s /c', 'node build/dev-server.js' ]
11 silly lifecycle vue-echarts@2.5.0~dev: Returned: code: 1  signal: null
12 info lifecycle vue-echarts@2.5.0~dev: Failed to exec dev script
13 verbose stack Error: vue-echarts@2.5.0 dev: `node build/dev-server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\nodejs\node_modules\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (D:\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid vue-echarts@2.5.0
15 verbose cwd E:\study\vue\vue-echarts
16 verbose Windows_NT 6.1.7601
17 verbose argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v8.4.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error vue-echarts@2.5.0 dev: `node build/dev-server.js`
22 error Exit status 1
23 error Failed at the vue-echarts@2.5.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

求指导，谢谢。

**Comment by Justineo** [comment]
我在 Windows 上无法重现这个问题……

**Comment by gdc5p** [comment]
OS: Debian GNU/Linux testing(code name: buster)
Node version: V8.9.3
npm version: V5.5.1

`npm run dev` 运行正常。

**Comment by Justineo** [comment]
暂时没能找到可以复现的环境，先关闭了。
