### ISSUE TITLE
npm run serve error

### ISSUE THREAD

**Issue by jiangyanjun1997** [ecomfe/vue-echarts#474]
## The type of this issue / Issue 类型
github代码直接运行错误
- [ ] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [ ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情
npm i
npm run serve时会报下面的错误

ERROR  Failed to compile with 1 errors                                                                                                                                                           4:47:04 PM

 error  in ./src/demo/main.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/czzs/echarts_vue/vue-echarts/node_modules/@babel/helper-compilation-targets/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:285:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:491:3)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:27)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/czzs/echarts_vue/vue-echarts/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/czzs/echarts_vue/vue-echarts/node_modules/@babel/preset-env/lib/index.js:11:14)

 @ multi (webpack)-dev-server/client?http://192.168.66.156:8080/sockjs-node (webpack)/hot/dev-server.js ./src/demo/main.js

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts/dist/vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

**Comment by vhxubo** [comment]
I fixed this issue by removing the `node_modules` directory and `package-lock.json` file then run `npm install` to fresh install all packages then the issue was fixed.

**Comment by Justineo** [comment]
Solved on fresh install so closing this.
