### ISSUE TITLE
nuxt添加 @nuxtjs/composition-api/module 后启动报错

### ISSUE THREAD

**Issue by otary** [ecomfe/vue-echarts#588]
### 

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
6.0.0
```

### Details

nuxt项目根据文档说明配置了`@nuxtjs/composition-api/module`模块，这个模块了里有句代码`this.addModule('unplugin-vue2-script-setup/nuxt')`，但实际上并没有这个模块，所以会导致报错！

```
 ERROR  Cannot find module 'unplugin-vue2-script-setup/nuxt'                                                                                                            16:14:41

  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
  at Function.resolve (internal/modules/cjs/helpers.js:33:19)
  at m (node_modules\jiti\dist\jiti.js:1:52953)
  at Resolver.f [as _require] (node_modules\jiti\dist\jiti.js:1:53766)
  at Resolver.requireModule (node_modules\@nuxt\core\dist\core.js:381:29)
  at ModuleContainer.addModule (node_modules\@nuxt\core\dist\core.js:182:38)
  at ModuleContainer.compositionApiModule2 (node_modules\@nuxtjs\composition-api\dist\module\index.js:193:8)
  at ModuleContainer.addModule (node_modules\@nuxt\core\dist\core.js:239:34)
  at promise.then (node_modules\@nuxt\utils\dist\utils.js:639:43)
  at process._tickCallback (internal/process/next_tick.js:68:7)

````

### Reproduction

test/test

**Comment by otary** [comment]
这是@nuxtjs/compsition-api 0.29.0版本的bug，切换到0.27.0就可以了
