### ISSUE TITLE
vue-echarts + nuxt brigde: Cannot read properties of undefined (reading '__extends')

### ISSUE THREAD

**Issue by warflash** [ecomfe/vue-echarts#647]
I'm wondering if any of you managed to get vue-echarts working on nuxt bridge?
For nuxt3 I found this template: https://stackblitz.com/edit/github-unqktr
But when applying the logic from there to a bridge project like so: https://stackblitz.com/edit/github-yashc5?file=pages/index.vue
the page wont load and this error is logged to the console:
```js
index.js?2dbb:2 Uncaught TypeError: Cannot read properties of undefined (reading '__extends')
    at eval (index.js?2dbb:2:1)
    at ./node_modules/echarts/node_modules/tslib/modules/index.js (app.js:5723:1)
    at __webpack_require__ (runtime.js:854:30)
    at fn (runtime.js:151:20)
    at Module.eval (echarts.js:47:63)
    at eval (echarts.js:2689:30)
    at ./node_modules/echarts/lib/core/echarts.js (app.js:4367:1)
    at __webpack_require__ (runtime.js:854:30)
    at fn (runtime.js:151:20)
    at eval (core.js?aa74:2:1)
```

_Originally posted by @warflash in https://github.com/ecomfe/vue-echarts/discussions/639_

**Comment by warflash** [comment]
FYI, this error can be resolved by aliasing tslib in nuxt.config. More info can be found here: https://github.com/nuxt/bridge/discussions/491#discussioncomment-3430976 
Closing for now as I'm not sure whether thats on nuxt or vue-echarts
