### ISSUE TITLE
 `setOption` should not be called during main process.

### ISSUE THREAD

**Issue by Valar103769** [ecomfe/vue-echarts#679]
### 请确认

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
echarts 没问题
```

### 问题详情

vue-chart还是eachrt的问题? 

  <vue-chart :option="option" style="height: 500px" />

### 问题复现

https://github.com/ecomfe/vue-echarts/issues/new?assignees=&labels=&template=bug-report.zh-Hans.yml

**Comment by Valar103769** [comment]
缺少配置项
  xAxis: {
        type: 'category', // 缺少
     
      },

**Comment by Valar103769** [comment]
Error: Invalide sourceFormat: unknown
    at assert (util.js:404:15)
    at mountMethods (dataProvider.js:120:9)
    at new DefaultDataProvider2 (dataProvider.js:82:5)
    at SourceManager2._innerGetDataStore (sourceManager.js:402:30)
    at SourceManager2._innerGetDataStore (sourceManager.js:398:35)
    at SourceManager2.getSharedDataStore (sourceManager.js:379:17)
    at createSeriesData (createSeriesData.js:149:49)
    at LineSeriesModel2.getInitialData (LineSeries.js:72:12)
    at SeriesModel2.init (Series.js:100:21)
    at GlobalModel2.<anonymous> (Global.js:381:28) Proxy {…} 'mounted hook'

**Comment by Justineo** [comment]
Please provide a minimal reproduction.
